### ISSUE TITLE
Options for dest_path and dest_loader_path

### ISSUE THREAD

**Issue by jjeising** [chearon/macpack#1]
It would be nice too add options for destination path and destination loader path, this would allow placing libraries in a separate folder when creating application bundles.

**Comment by chearon** [comment]
I'm almost finished with this! Curious, is there any reason why they couldn't be specified by the same option? For example, if the binary is `/a/b/program` couldn't the option just be a folder relative to the directory containing the binary? e.g. `--dir=../libs` which would copy the binaries into `/a/libs` and the loader path would automatically be `@executable_path/../../libs/<library>`?

I have it pretty much the same way as macdylibbundler right now but I can't think of a scenario where they'd be different. I haven't made an app bundle yet though

**Comment by jjeising** [comment]
I think combining is a good idea. You just have to resolve the destination path relative to the binary location (`./macpack -d ../libs path/to/binary` should result in `path/libs`).
The only reason to separate these is when you would like to copy the binary to a different location after modification without moving the libraries, but I don't think this is necessary at all.

**Comment by chearon** [comment]
I got that done using `os.relpath` to find location of libs relative to the binary folder. New option is `-d`. And yeah, I think it's safe to assume you wouldn't really want to move them after modification... If they specify an absolute path in `-d` it won't do any relative stuff

Thanks!

**Comment by jjeising** [comment]
Tested, everything is good (even with new `@loader_path`). Thank you very much!
